# Generated by Django 4.2.2 on 2023-07-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='duration_unit',
            field=models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes')], default='seconds', max_length=10),
        ),
    ]
